### ISSUE TITLE
Doesn't appear to block as expected

### ISSUE THREAD

**Issue by ttomsu** [softprops/turnstyle#5] opened 2020-06-10 15:37 UTC
Hi! I like the idea of this plugin, but can't seem to get it working as expected.

I only have 1 workflow, so I'd expect it to block at _some_ point, but doesn't appear to. Can you check if there is something in our workflow that causes it to break an assumption you had when writing this action?

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/.github/workflows/buildAndTest.yaml#L97-L102

Thanks,
Travis

**Comment by praneetloke** [comment] 2020-06-18 17:57
@ttomsu you workflow shows that you used the [`continue-after-seconds`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/.github/workflows/buildAndTest.yaml#L112) property. That will cause `turnstyle` to proceed after having waited that long, so if your other workflow is still running, now the previously-waited workflow will also continue past the `turnstyle` step. If that's not what you want, you should not pass a value for that property.

**Comment by softprops** [comment] 2020-06-27 04:54
That's correct. The tale tell sign will be this message in your action logs

https://github.com/softprops/turnstyle/blob/64882c20d87df5b6d5c722af0e8c2206404a1f44/src/wait.ts#L31

I'm going to close this issue for now because this is expected behavior for that configuration. Feel free reopen with a link to your action logs if you continue to see this without the continue after setting

**Closed by softprops** 2020-06-27 04:54 UTC
